### ISSUE TITLE
Regarding training issues with the BIPED dataset

### ISSUE THREAD

**Issue by shuttle999** [DREAMXFAR/FCL-Net#2]
Hi, thanks for your excellent work! I have several questions about training the BIPED dataset that I would like to consult with you:
1、Is the training of the BIPED dataset performed using augmented data, or is it conducted on the original data of 250 images with data augmentation?
2、Could you kindly provide the configuration and dataset.py files for training BIPED? If it's convenient for you to share, please send them to my email: [shuttle@hnu.edu.cn](mailto:shuttle@hnu.edu.cn). I would greatly appreciate your assistance.

**Comment by DREAMXFAR** [comment]
Our model is trained with the original data of 250 images with data augmentation following an old version of https://github.com/xavysp/MBIPED (note that this is the official implementation of BIPED and it has been updated). We recommend you to see this project for dataset details, as well as dataset.py. To reuse our `datasets.py`, you only need to generate `data/train_pair.lst` for your dataset.
